### ISSUE TITLE
[TODO] Proofreading and add image to README

### ISSUE THREAD

**Issue by tlkh** [OpenSUTD/face-of-fonts#2]
- [ ] Proofread and formatting
- [x] Add images to readme
- [ ] Add explanation for which files do what in the repository
- [ ] Add to OpenSUTD website projects list

**Comment by Emrys-Hong** [comment]
Just have added image to Readme
